version: ‘3’
services:
  web:
    container_name: "django_kakeibo"
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    working_dir: /code
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    container_name: "コンテナ名"
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "データベース名"
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: ‘yes’
      volumes:
        — ./mysql:/var/lib/mysql
      ports:
        — 3306:3306