version: '3'
services:
  db:
    container_name: KakeiboDB
    platform: linux/x86_64 #この行を追加。これないと"ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries"
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_DATABASE: Kakeibo
      # MYSQL_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_USER: root
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: u585304g
      MYSQL_PASSWORD: pwd
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes" #これ追加
      TZ: Asia/Tokyo
      # MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      # MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
      volumes:
        — KakeiboDB.volume:/var/lib/mysql
        — ./mysql/conf.d:/etc/mysql/conf.d
        - ./sql:/initdb.d
      ports:
        — 3306:3306
    # command: mysql -u $MYSQL_ROOT_USER -p $MYSQL_ROOT_PASSWORD
    # command: mysqld --innodb_use_native_aio=
    expose:
      - "3306"
  
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   ports:
  #     - 8080:80
  #   environment:
  #     - PMA_HOST=db
  #     - PMA_USER=root
  #     - PMA_PASSWORD=password
  web:
    container_name: "django_kakeibo"
    platform: linux/amd64
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    working_dir: /code
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    # extra_hosts:                  # 追加
    #   - localhost:172.21.0.3   # 追加