# Generated by Django 3.2.15 on 2022-08-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0002_alter_payment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcategory',
            name='name',
            field=models.CharField(max_length=16, verbose_name='カテゴリ名'),
        ),
    ]
