# Generated by Django 3.2.15 on 2022-09-14 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0005_bankcategory_rest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rest',
            name='date',
        ),
    ]
