# Generated by Django 3.2.15 on 2022-09-15 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0006_remove_rest_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rest',
            old_name='bank_category',
            new_name='category',
        ),
    ]
