# Generated by Django 3.2.15 on 2022-09-15 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0007_rename_bank_category_rest_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rest',
            name='rest',
            field=models.IntegerField(verbose_name='金額'),
        ),
    ]
