# Generated by Django 3.2.15 on 2022-09-15 02:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0008_alter_rest_rest'),
    ]

    operations = [
        migrations.AddField(
            model_name='rest',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='日付'),
        ),
    ]
